language: generic
os: linux
dist: trusty
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - g++-6
      - llvm-5.0-dev
      - libedit-dev
      - cmake
      - doxygen
      - graphviz
env:
  - CC=gcc-6 CXX=g++-6
before_script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DVSL_INCLUDE_TESTS=On ..
script:
  - make
  - make check
  - make docs
