language: generic
os: linux
dist: trusty
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - g++-6
      - clang-5.0
      - llvm-5.0-dev
      - libedit-dev
      - cmake
      - doxygen
      - graphviz
matrix:
  include:
    - env: CC=gcc-6 CXX=g++-6 BUILD_TYPE=Debug
    - env: CC=gcc-6 CXX=g++-6 BUILD_TYPE=Release
    - env: CC=clang-5.0 CXX=clang++-5.0 BUILD_TYPE=Debug
    - env: CC=clang-5.0 CXX=clang++-5.0 BUILD_TYPE=Release
before_script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DVSL_INCLUDE_TESTS=On ..
script:
  - make
  - make check
  - make docs
